server:
  port: 9999
  servlet:
    context-path: /api

spring:
  application:
    name: ShareHub-app
  mail:
    host:  smtp.mailtrap.io
    port: 2525
    username: 80005ffb44019b
    password: 515c1e70b3cf35
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/share_hub_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization

firebase:
  config:
    apiKey: "AIzaSyBovpBAybWr0ZTCnHr74Z36j86xQUQoK18"
    authDomain: "share-hub-4607b.firebaseapp.com"
    projectId: "share-hub-4607b"
    storageBucket: "share-hub-4607b.appspot.com"
    messagingSenderId: "490893571259"
    appId: "1:490893571259:web:f163ced78ce95ce4fca59e"
    measurementId: "G-QVGJ4TC4G4"