server:
  port: $PORT
  servlet:
    context-path: /api

spring:
  application:
    name: ShareHub-app
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${DATABASE_URL}
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization

firebase:
  bucketName: ${FIREBASE_BUCKET_NAME}
  type: ${FIREBASE_TYPE}
  projectId: ${FIREBASE_PROJECT_ID}
  privateKeyId: ${FIREBASE_PRIVATE_KEY_ID}
  privateKey: ${FIREBASE_PRIVATE_KEY}
  clientEmail: ${FIREBASE_CLIENT_EMAIL}
  clientId: ${FIREBASE_CLIENT_ID}
  authUri: ${FIREBASE_AUTH_URI}
  tokenUri: ${FIREBASE_TOKEN_URI}
  authProvider_x509_cert_url: ${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
  client_x509_cert_url: ${FIREBASE_CLIENT_X509_CERT_URL}
